# -*- coding: utf-8 -*-
"""
日期小时差计算模块

生成日期: 2026-02-27
模型版本: Claude Opus 4.6 (claude-opus-4-6)
开发者签名: Generated by Claude Code - Anthropic

描述:
    提供计算两个日期/时间之间小时差的工具函数。
    支持字符串和 datetime 对象两种输入方式。
"""

from datetime import datetime
from typing import Union


def calc_hour_diff(
    start: Union[str, datetime],
    end: Union[str, datetime],
    fmt: str = "%Y-%m-%d %H:%M:%S",
) -> float:
    """计算两个日期时间之间的小时差。

    Args:
        start: 起始时间，可以是 datetime 对象或符合 fmt 格式的字符串。
        end:   结束时间，同上。
        fmt:   当输入为字符串时使用的解析格式，默认 "%Y-%m-%d %H:%M:%S"。

    Returns:
        小时差的绝对值（float），保留两位小数。

    Raises:
        ValueError: 字符串无法按指定格式解析时抛出。
        TypeError:  输入类型既非 str 也非 datetime 时抛出。

    Examples:
        >>> calc_hour_diff("2025-01-01 00:00:00", "2025-01-02 12:00:00")
        36.0
        >>> calc_hour_diff(datetime(2025, 3, 1), datetime(2025, 3, 1, 6, 30))
        6.5
    """
    # 统一转换为 datetime 对象
    start_dt = _to_datetime(start, fmt)
    end_dt = _to_datetime(end, fmt)

    # 计算时间差，取绝对值避免方向问题
    delta = abs((end_dt - start_dt).total_seconds())

    # 秒转小时，保留两位小数
    hours = round(delta / 3600, 2)
    return hours


def _to_datetime(value: Union[str, datetime], fmt: str) -> datetime:
    """将输入统一转换为 datetime 对象。

    Args:
        value: 待转换的值。
        fmt:   字符串解析格式。

    Returns:
        转换后的 datetime 对象。
    """
    if isinstance(value, datetime):
        return value

    if isinstance(value, str):
        return datetime.strptime(value, fmt)

    raise TypeError(
        f"期望 str 或 datetime 类型，收到 {type(value).__name__}"
    )


# ---- 直接运行时的演示 ----
if __name__ == "__main__":
    # 示例 1: 字符串输入
    result = calc_hour_diff("2025-06-01 08:00:00", "2025-06-03 20:30:00")
    print(f"示例1 — 字符串输入:  {result} 小时")

    # 示例 2: datetime 对象输入
    dt1 = datetime(2025, 1, 1, 0, 0, 0)
    dt2 = datetime(2025, 1, 2, 12, 0, 0)
    result2 = calc_hour_diff(dt1, dt2)
    print(f"示例2 — datetime输入: {result2} 小时")

    # 示例 3: 仅日期（自定义格式）
    result3 = calc_hour_diff("2025-03-01", "2025-03-15", fmt="%Y-%m-%d")
    print(f"示例3 — 仅日期输入:  {result3} 小时")
